### ISSUE TITLE
Invalid host name

### ISSUE THREAD

**Issue by vudev** [v3rm0n/addon-shairport-sync#2]
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Failed to create server: Invalid host name
avahi-daemon 0.7 exiting.
./run: line 7: /usr/lib/hassio-addons/base.sh: No such file or directory
./run: line 16: hass.debug: command not found
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Failed to create server: Invalid host name
avahi-daemon 0.7 exiting.
./run: line 7: /usr/lib/hassio-addons/base.sh: No such file or directory
./run: line 16: hass.debug: command not found
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Failed to create server: Invalid host name
avahi-daemon 0.7 exiting.
./run: line 7: /usr/lib/hassio-addons/base.sh: No such file or directory
./run: line 16: hass.debug: command not found
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Failed to create server: Invalid host name
avahi-daemon 0.7 exiting.
./run: line 7: /usr/lib/hassio-addons/base.sh: No such file or directory
./run: line 16: hass.debug: command not found
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Failed to create server: Invalid host name
avahi-daemon 0.7 exiting.

**Comment by adymanis** [comment]
Had same issues when I tried using this add-on. Fixed in PR: https://github.com/v3rm0n/addon-shairport-sync/pull/3

**Comment by v3rm0n** [comment]
Fixed in 0.0.3
